# Generated by Django 4.2.1 on 2023-05-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('productprice', models.CharField(blank=True, max_length=100, null=True)),
                ('totalproduct', models.CharField(blank=True, max_length=100, null=True)),
                ('productimagee', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
