# Generated by Django 4.2.1 on 2023-05-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_cartdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartdb',
            new_name='carttdb',
        ),
    ]
