# Generated by Django 4.2.1 on 2023-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_carttdb_productimagee_remove_carttdb_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdetaildb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('emaill', models.CharField(blank=True, max_length=30, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
