# Generated by Django 4.2.1 on 2023-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_carttdb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttdb',
            name='productlanguage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
