# Generated by Django 4.2.1 on 2023-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_carttdb_productlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttdb',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='document'),
        ),
    ]
