# Generated by Django 3.2.10 on 2023-06-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttdb',
            name='pdf',
        ),
    ]
