# Generated by Django 4.2.1 on 2023-06-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_carttdb_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttdb',
            name='productimagee',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
