# Generated by Django 4.2.1 on 2023-06-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_carttdb_productimagee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttdb',
            name='productimagee',
        ),
    ]
