# Generated by Django 4.2.1 on 2023-06-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_carttdb_productimagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttdb',
            name='productimagee',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
