# Generated by Django 3.2.10 on 2023-06-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_carttdb_productimagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetaildb',
            name='productname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='productprice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetaildb',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
