# Generated by Django 4.2.1 on 2023-06-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_auto_20230616_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttdb',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='document'),
        ),
    ]
