# Generated by Django 4.2.1 on 2023-06-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_carttdb_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetaildb',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='paymentdetaildb',
            name='productprice',
        ),
        migrations.RemoveField(
            model_name='paymentdetaildb',
            name='total',
        ),
    ]
