# Generated by Django 4.2 on 2023-04-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acdb',
            old_name='image',
            new_name='imagee',
        ),
    ]
