# Generated by Django 4.2 on 2023-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_rename_image_acdb_imagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='acdb',
            name='genres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
