# Generated by Django 4.2 on 2023-04-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_apdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apdb',
            name='Page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
