# Generated by Django 4.2 on 2023-04-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_apdb_page_alter_apdb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apdb',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
