# Generated by Django 4.2 on 2023-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_remove_acdb_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='apdb',
            name='Author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='apdb',
            name='Date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apdb',
            name='Language',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='apdb',
            name='Publisher',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
