# Generated by Django 4.2 on 2023-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_apdb_author_apdb_date_apdb_language_apdb_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apdb',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
