# Generated by Django 4.2 on 2023-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_alter_apdb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apdb',
            name='Rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
