# Generated by Django 4.2.1 on 2023-06-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_gndb'),
    ]

    operations = [
        migrations.AddField(
            model_name='apdb',
            name='Pdf',
            field=models.FileField(blank=True, null=True, upload_to='document'),
        ),
    ]
