# Generated by Django 3.2.10 on 2023-06-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_apdb_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='apdb',
            name='AuthorLink',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
